export const categories = [
  "Tous",
  "Art Digital",
  "Collectibles",
  "Musique",
  "Sport",
  "Photographie",
  "Gaming",
  "Domaines",
  "Mèmes",
];

export const MenuItems = [
  {
    name: "My collections",
    link: "/my-nfts",
  },
  {
    name: "Marketplace",
    link: "/marketplace",
  },
  {
    name: "Sell",
    link: "/create",
  },
  {
    name: "Dashboard",
    link: "/dashboard",
  },
];

export const allNFTs = [
  {
    id: 1,
    title: "Neon Dreams #423",
    price: "1.25 ETH",
    priceUSD: "$2,150",
    artist: "CyberArtist",
    timeLeft: "6h 23m",
    purchaseDate: "18 Feb 2025",
    likes: 124,
    image: "/images/nft1.jpg",
    category: "Art Digital",
    description: "A vibrant digital artwork exploring neon aesthetics",
    owner: "0x1234567890123456789012345678901234567890",
    creator: "0x9876543210987654321098765432109876543210",
  },
  {
    id: 2,
    title: "Quantum Realm #89",
    price: "0.78 ETH",
    priceUSD: "$1,340",
    artist: "DigitalEther",
    timeLeft: "2h 05m",
    likes: 87,
    image: "/images/nft2.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Collectibles",
  },
  {
    id: 3,
    title: "Abstract Future #12",
    artist: "NeoBrush",
    timeLeft: "12h 40m",
    price: "2.15 ETH",
    priceUSD: "$3,698",
    likes: 209,
    image: "/images/nft3.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Art Digital",
  },
  {
    id: 4,
    title: "Retro Pixel #345",
    artist: "Pixel8",
    price: "0.45 ETH",
    priceUSD: "$774",
    timeLeft: "3h 12m",
    likes: 65,
    image: "/images/nft4.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Gaming",
  },
  {
    id: 5,
    title: "Cosmic Voyage #72",
    artist: "StarDust",
    price: "1.85 ETH",
    priceUSD: "$3,182",
    timeLeft: "9h 18m",
    likes: 176,
    image: "/images/nft5.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Art Digital",
  },
  {
    id: 6,
    title: "Digital Soul #221",
    artist: "ByteCreator",
    price: "3.20 ETH",
    priceUSD: "$5,504",
    timeLeft: "4h 55m",
    likes: 312,
    image: "/images/nft6.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Musique",
  },
  {
    id: 7,
    title: "Cyberwave #77",
    artist: "NeonWave",
    price: "1.12 ETH",
    priceUSD: "$1,926",
    timeLeft: "8h 10m",
    likes: 145,
    image: "/images/nft7.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Art Digital",
  },
  {
    id: 8,
    title: "Stellar Odyssey #419",
    artist: "GalacticMind",
    price: "2.70 ETH",
    priceUSD: "$4,644",
    timeLeft: "5h 30m",
    likes: 231,
    image: "/images/nft8.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Collectibles",
  },
  {
    id: 9,
    title: "Virtual Dimension #34",
    artist: "DigitalDreamer",
    price: "0.95 ETH",
    priceUSD: "$1,634",
    timeLeft: "7h 45m",
    likes: 102,
    image: "/images/nft9.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Gaming",
  },
  {
    id: 10,
    title: "Ethereal Soundscape #56",
    artist: "AudioVisual",
    price: "1.68 ETH",
    priceUSD: "$2,890",
    timeLeft: "10h 20m",
    likes: 185,
    image: "/images/nft10.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Musique",
  },
  {
    id: 11,
    title: "Digital Genesis #128",
    artist: "CryptoCreator",
    price: "4.35 ETH",
    priceUSD: "$7,482",
    timeLeft: "1h 15m",
    likes: 340,
    image: "/images/nft11.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Art Digital",
  },
  {
    id: 12,
    title: "Techno Illusion #99",
    artist: "VirtualVision",
    price: "2.25 ETH",
    priceUSD: "$3,870",
    timeLeft: "6h 50m",
    likes: 197,
    image: "/images/nft12.jpg",
    purchaseDate: "18 Feb 2025",
    category: "Art Digital",
  },
];
